# Generated by Django 4.2 on 2023-05-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_delete_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
